//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        public int codigoalumno { get; set; }
        public string nombrealumno { get; set; }
        public string materiaalumno { get; set; }
        public string carreraalumno { get; set; }
        public int telefono { get; set; }
    }
}
